### ISSUE TITLE
Counting bug

### ISSUE THREAD

**Issue by soudblox** [NaruDevnote/yagpdb-ccs#7]
![image](https://user-images.githubusercontent.com/73058244/101229925-2dd80d80-36d5-11eb-9545-7fab79ab62b8.png)
if you do [prefix]count [mention yourself] it will error that

**Comment by NaruDevnote** [comment]
Issue was a small mistype of a variable name (was supposed to be `$u` not `$c` lol)

**Comment by soudblox** [comment]
lmfao

**Comment by NaruDevnote** [comment]
Merged the fix now so it should be all good 👍
